### ISSUE TITLE
Поддержка русскоязычной капчи

### ISSUE THREAD

**Issue by hyperplural** [imartemy1524/vk_captcha#4]
Привет. Подскажи, будет ли в будущем реализована поддержка распознавания русскоязычной капчи для модели?

![captcha (1)](https://github.com/imartemy1524/vk_captcha/assets/33278849/8b7aed3d-cd4d-481b-8aa7-968ee89008cf) ![captcha](https://github.com/imartemy1524/vk_captcha/assets/33278849/73adc9d5-3499-4a20-beea-7a39c17b8d05)

 Появляются в таком диапазоне sid `https://vk.com/captcha.php?sid=121789838075&resized=1&width=400`

**Comment by imartemy1524** [comment]
Поддержка рускоязычной капчи пока не планируется, хотя при желании можно без проблем обучить модель на распознание русских букв аналогичным способом.

**Comment by Azarattum** [comment]
Есть ли способ заставить вк всегда отправлять агло-язычные капчи?
