### ISSUE TITLE
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled

### ISSUE THREAD

**Issue by DUB1401** [imartemy1524/vk_captcha#8]
Please, add supporting for [onnxruntime](https://github.com/microsoft/onnxruntime) version 1.16.x and newer, because they crashes script with error:

`ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled`

Also you may describe [onnxruntime](https://github.com/microsoft/onnxruntime) required version in your [requirements.txt](https://github.com/imartemy1524/vk_captcha/blob/main/requirements.txt).

[Link](https://github.com/modelscope/facechain/issues/319) to same issue and problem solution.

**Comment by SlowMotion241** [comment]
I have same error

**Comment by DUB1401** [comment]
> I have same error

You may install [onnxruntime](https://github.com/microsoft/onnxruntime) version [1.15.1](https://github.com/microsoft/onnxruntime/releases/tag/v1.15.1). I think this is a temporary solution, but it works.

```
pip install onnxruntime==1.15.1
```

**Comment by SlowMotion241** [comment]
> > I have same error
> 
> You may install [onnxruntime](https://github.com/microsoft/onnxruntime) version [1.15.1](https://github.com/microsoft/onnxruntime/releases/tag/v1.15.1). I think this is a temporary solution, but it works.
> 
> ```
> pip install onnxruntime==1.15.1
> ```

Yes. Its help me) Thank you

**Comment by DUB1401** [comment]
This issue has been resolved in [onnxruntime](https://github.com/microsoft/onnxruntime) version [1.16.1](https://github.com/microsoft/onnxruntime/releases/tag/v1.16.1). All you need is to update the library.

```
pip install onnxruntime -U
```
